title: "Hexa's blog"
email: nguyenvinhlinh93@gmail.com
description: The more you learn, the easier you learn more!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hexalink.xyz" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: "https://twitter.com/LinhNguyenV"
github_username:  "https://github.com/nguyenvinhlinh"
facebook_username: "https://www.facebook.com/LinkBall"
steam_url: "https://steamcommunity.com/id/LinkVN/"
timezone: Asia/Bangkok
paginate: 10
permalink: /:slugified_categories/:year/:month/:day/:title:output_ext

# Build settings
markdown: kramdown
highlighter: rouge

sass:
  sass_dir: _sass
plugins:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
future: true
incremental: true
port: 3001
verbose: true
