title: "Hexa's blog"
email: nguyenvinhlinh93@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nguyenvinhlinh.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: "https://twitter.com/LinhNguyenV"
github_username:  "https://github.com/nguyenvinhlinh"
facebook_username: "https://www.facebook.com/LinkBall"
steam_url: "https://steamcommunity.com/id/LinkVN/"
timezone: Asia/Bangkok
paginate: 10

# Build settings
markdown: kramdown
highlighter: rouge

sass:
  sass_dir: _sass
gems:
  - jekyll-feed
  - jekyll-paginate
  - octopress-debugger
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
future: true
incremental: true
port: 3000
verbose: true
